@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Mar 05 00:29:05 +0000 2024
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim RAM_tb_behav -key {Behavioral:sim_1:Functional:RAM_tb} -tclbatch RAM_tb.tcl -view C:/Users/desig/Documents/FPGA/FPGA_Projects/Vivado_Projects/RAM/RAM_test/RAM_tb_behav.wcfg -log simulate.log"
call xsim  RAM_tb_behav -key {Behavioral:sim_1:Functional:RAM_tb} -tclbatch RAM_tb.tcl -view C:/Users/desig/Documents/FPGA/FPGA_Projects/Vivado_Projects/RAM/RAM_test/RAM_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
