@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Sat Mar 16 23:37:39 +0000 2024
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto 6176b5620dad4da78db2b14c0ed41b80 --incr --debug typical --relax --mt 2 -L work -L secureip --snapshot I2C_controller.vhd_behav work.I2C_controller.vhd -log elaborate.log"
call xelab  -wto 6176b5620dad4da78db2b14c0ed41b80 --incr --debug typical --relax --mt 2 -L work -L secureip --snapshot I2C_controller.vhd_behav work.I2C_controller.vhd -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
