# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
set_param synth.incrementalSynthesisCache C:/Users/desig/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-1096-DESKTOP-7RQ9HLB/incrSyn
set_param xicom.use_bs_reader 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/desig/Documents/GitHub/FPGA_Projects/Vivado_Projects/i2cTest/i2c_Test/i2c_Test.cache/wt [current_project]
set_property parent.project_path C:/Users/desig/Documents/GitHub/FPGA_Projects/Vivado_Projects/i2cTest/i2c_Test/i2c_Test.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/desig/Documents/GitHub/FPGA_Projects/Vivado_Projects/i2cTest/i2c_Test/i2c_Test.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -vhdl2008 -library xil_defaultlib {
  C:/Users/desig/Documents/GitHub/FPGA_Projects/Vivado_Projects/i2cTest/src/I2C_controllerNew.vhd
  C:/Users/desig/Documents/GitHub/FPGA_Projects/Vivado_Projects/i2cTest/src/i2cTest.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/desig/Documents/GitHub/FPGA_Projects/Vivado_Projects/i2cTest/i2c_Test/i2c_Test.srcs/constrs_1/new/I2C.xdc
set_property used_in_implementation false [get_files C:/Users/desig/Documents/GitHub/FPGA_Projects/Vivado_Projects/i2cTest/i2c_Test/i2c_Test.srcs/constrs_1/new/I2C.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top i2cTest -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef i2cTest.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file i2cTest_utilization_synth.rpt -pb i2cTest_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
