set_property IOSTANDARD LVTTL [get_ports {GPIO[0]}]
set_property IOSTANDARD LVTTL [get_ports {GPIO[1]}]
set_property IOSTANDARD LVTTL [get_ports {GPIO[2]}]
set_property PACKAGE_PIN W5 [get_ports clk_100MHz]
set_property IOSTANDARD LVTTL [get_ports clk_100MHz]
set_property PACKAGE_PIN M19 [get_ports {GPIO[0]}]
set_property PACKAGE_PIN P17 [get_ports {GPIO[1]}]
set_property PACKAGE_PIN R18 [get_ports {GPIO[2]}]

set_property IOSTANDARD LVTTL [get_ports LED]
set_property PACKAGE_PIN U16 [get_ports LED]

set_property BITSTREAM.CONFIG.OVERTEMPPOWERDOWN ENABLE [current_design]
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]

set_property IOSTANDARD LVTTL [get_ports {ANODE[1]}]
set_property IOSTANDARD LVTTL [get_ports {ANODE[2]}]
set_property IOSTANDARD LVTTL [get_ports {ANODE[3]}]
set_property IOSTANDARD LVTTL [get_ports {ANODE[4]}]
set_property IOSTANDARD LVTTL [get_ports {segment[1]}]
set_property IOSTANDARD LVTTL [get_ports {segment[2]}]
set_property IOSTANDARD LVTTL [get_ports {segment[3]}]
set_property IOSTANDARD LVTTL [get_ports {segment[4]}]
set_property IOSTANDARD LVTTL [get_ports {segment[5]}]
set_property IOSTANDARD LVTTL [get_ports {segment[6]}]
set_property IOSTANDARD LVTTL [get_ports {segment[7]}]
set_property PACKAGE_PIN U2 [get_ports {ANODE[1]}]
set_property PACKAGE_PIN U4 [get_ports {ANODE[2]}]
set_property PACKAGE_PIN V4 [get_ports {ANODE[3]}]
set_property PACKAGE_PIN W4 [get_ports {ANODE[4]}]
set_property PACKAGE_PIN W7 [get_ports {segment[1]}]
set_property PACKAGE_PIN W6 [get_ports {segment[2]}]
set_property PACKAGE_PIN U8 [get_ports {segment[3]}]
set_property PACKAGE_PIN V8 [get_ports {segment[4]}]
set_property PACKAGE_PIN U5 [get_ports {segment[5]}]
set_property PACKAGE_PIN V5 [get_ports {segment[6]}]
set_property PACKAGE_PIN U7 [get_ports {segment[7]}]
