#clock constraints
create_clock -period 10.000 -name clk_100MHz -waveform {0.000 5.000} [get_ports clk_100MHz]

#pin assignments
set_property PACKAGE_PIN E3  [get_ports clk_100MHz]
set_property PACKAGE_PIN N17 [get_ports rst]
set_property PACKAGE_PIN T10 [get_ports {SEGMENT[0]}]
set_property PACKAGE_PIN R10 [get_ports {SEGMENT[1]}]
set_property PACKAGE_PIN K16 [get_ports {SEGMENT[2]}]
set_property PACKAGE_PIN K13 [get_ports {SEGMENT[3]}]
set_property PACKAGE_PIN P15 [get_ports {SEGMENT[4]}]
set_property PACKAGE_PIN T11 [get_ports {SEGMENT[5]}]
set_property PACKAGE_PIN L18 [get_ports {SEGMENT[6]}]
set_property PACKAGE_PIN U13 [get_ports {AN[7]}]
set_property PACKAGE_PIN K2  [get_ports {AN[6]}]
set_property PACKAGE_PIN T14 [get_ports {AN[5]}]
set_property PACKAGE_PIN P14 [get_ports {AN[4]}]
set_property PACKAGE_PIN J14 [get_ports {AN[3]}]
set_property PACKAGE_PIN T9  [get_ports {AN[2]}]
set_property PACKAGE_PIN J18 [get_ports {AN[1]}]
set_property PACKAGE_PIN J17 [get_ports {AN[0]}]

#set JTAG configuration block voltage
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]

#IO Standards
set_property IOSTANDARD LVTTL [get_ports clk_100MHz]
set_property IOSTANDARD LVTTL [get_ports rst]
set_property IOSTANDARD LVTTL [get_ports {SEGMENT[0]}]
set_property IOSTANDARD LVTTL [get_ports {SEGMENT[1]}]
set_property IOSTANDARD LVTTL [get_ports {SEGMENT[2]}]
set_property IOSTANDARD LVTTL [get_ports {SEGMENT[3]}]
set_property IOSTANDARD LVTTL [get_ports {SEGMENT[4]}]
set_property IOSTANDARD LVTTL [get_ports {SEGMENT[5]}]
set_property IOSTANDARD LVTTL [get_ports {SEGMENT[6]}]
set_property IOSTANDARD LVTTL [get_ports {AN[7]}]
set_property IOSTANDARD LVTTL [get_ports {AN[6]}]
set_property IOSTANDARD LVTTL [get_ports {AN[5]}]
set_property IOSTANDARD LVTTL [get_ports {AN[4]}]
set_property IOSTANDARD LVTTL [get_ports {AN[3]}]
set_property IOSTANDARD LVTTL [get_ports {AN[2]}]
set_property IOSTANDARD LVTTL [get_ports {AN[1]}]
set_property IOSTANDARD LVTTL [get_ports {AN[0]}]
